version: 2
jobs:
  build-test:
    docker:
      - image: circleci/php:5.6
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: composer install
      - run: vendor/bin/phpunit -c phpunit.xml.dist
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-test
